server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://39.99.60.110:3306/theripe?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 5201314
  thymeleaf:
    cache: false
    suffix: .html
    encoding: UTF-8
    content-type: text/html; charset=utf-8

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
